### ISSUE TITLE
Solution reference

### ISSUE THREAD

**Issue by gbrusella** [ow-en/ASPCoreVueCLITemplate#1]
The solution file points to "AtlasOneCore\VueCLICore.csproj". I think it should point to "VueCLICore\VueCLICore.csproj

**Comment by ow-en** [comment]
Sorry for the late response - you're correct. I'll push the change tonight- thanks!

**Comment by User00015** [comment]
Whatever happened to this change?

**Comment by ow-en** [comment]
Sorry about the delay on this - it's been a busy time and didn't get around to it. The fix has been merged 1/22 thanks to @bishopsmove contribution.
